// Generated by web/gen-catalog.mjs — do not edit by hand.
// Source of truth: apps/mac/web/src/savers.ts

struct SaverEntry {
  let id: String
  let label: String
}

enum SaverCatalog {
  static let all: [SaverEntry] = [
    SaverEntry(id: "toasters", label: "Flying Toasters"),
    SaverEntry(id: "dvd", label: "DVD Bouncing Logo"),
    SaverEntry(id: "warp", label: "Warp"),
    SaverEntry(id: "fish", label: "Fish Aquarium"),
    SaverEntry(id: "rainstorm", label: "Rainstorm"),
    SaverEntry(id: "hard-rain", label: "Hard Rain"),
    SaverEntry(id: "globe", label: "Globe"),
    SaverEntry(id: "fade-out", label: "Fade Out"),
    SaverEntry(id: "bouncing-ball", label: "Bouncing Ball"),
    SaverEntry(id: "logo", label: "Logo"),
    SaverEntry(id: "messages", label: "Messages"),
    SaverEntry(id: "messages2", label: "Messages II"),
    SaverEntry(id: "pipes", label: "Pipes"),
    SaverEntry(id: "bsod", label: "BSOD"),
    SaverEntry(id: "flurry", label: "Flurry"),
    SaverEntry(id: "fluid", label: "Fluid"),
    SaverEntry(id: "reaction-diffusion", label: "Reaction Diffusion"),
    SaverEntry(id: "snowfall", label: "Snowfall"),
    SaverEntry(id: "lanterns", label: "Night Lanterns"),
    SaverEntry(id: "sakura", label: "Sakura Drift"),
    SaverEntry(id: "dev-dashboard", label: "Dev Dashboard"),
  ]
  static var ids: [String] { all.map(\.id) }
}
