// Generated by web/gen-catalog.mjs — do not edit by hand.
// Source of truth: apps/mac/web/src/savers.ts

struct SaverEntry {
  let id: String
  let label: String
}

enum SaverCatalog {
  static let all: [SaverEntry] = [
    SaverEntry(id: "toasters", label: "Flying Toasters"),
    SaverEntry(id: "dvd", label: "Bouncing Logo"),
    SaverEntry(id: "warp", label: "Warp"),
    SaverEntry(id: "fish", label: "Fish Aquarium"),
    SaverEntry(id: "rainstorm", label: "Rainstorm"),
    SaverEntry(id: "hard-rain", label: "Hard Rain"),
    SaverEntry(id: "globe", label: "Globe"),
    SaverEntry(id: "fade-out", label: "Fade Out"),
    SaverEntry(id: "bouncing-ball", label: "Bouncing Ball"),
    SaverEntry(id: "messages", label: "Messages"),
    SaverEntry(id: "pipes", label: "Pipes"),
    SaverEntry(id: "bsod", label: "BSOD"),
    SaverEntry(id: "flurry", label: "Flurry"),
    SaverEntry(id: "fluid", label: "Fluid"),
    SaverEntry(id: "reaction-diffusion", label: "Reaction Diffusion"),
    SaverEntry(id: "mystify", label: "Mystify"),
    SaverEntry(id: "metaquarium", label: "Metaquarium"),
    SaverEntry(id: "snowfall", label: "Snowfall"),
    SaverEntry(id: "lanterns", label: "Night Lanterns"),
    SaverEntry(id: "sakura", label: "Sakura Drift"),
    SaverEntry(id: "dev-dashboard", label: "Control Center"),
    SaverEntry(id: "aquarium", label: "Aquarium"),
    SaverEntry(id: "aurora", label: "Aurora"),
    SaverEntry(id: "comets", label: "Comet Shower"),
    SaverEntry(id: "constellation", label: "Constellation"),
    SaverEntry(id: "matrix-rain", label: "Matrix Rain"),
    SaverEntry(id: "nostalghia-candle", label: "Nostalghia's Candle"),
    SaverEntry(id: "orrery", label: "Orrery"),
    SaverEntry(id: "polygons", label: "Polygons"),
    SaverEntry(id: "procession", label: "Night Procession"),
    SaverEntry(id: "rain", label: "Rain"),
    SaverEntry(id: "warp-tunnel", label: "Warp Tunnel"),
  ]
  static var ids: [String] { all.map(\.id) }
}
