/**
 * Generates Sources/IdleScreens/SaverCatalog.swift and dist/savers.json from
 * the single source of truth in src/savers.ts, so the native menu and the web
 * page ship the exact same saver list. Run before `swift build`.
 */
import { build } from 'esbuild';
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const tmp = 'dist/.catalog.mjs';
mkdirSync('dist', { recursive: true });

await build({
  entryPoints: ['src/savers.ts'],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  outfile: tmp,
});

const { SAVER_CATALOG } = await import(pathToFileURL(tmp).href);
rmSync(tmp);

writeFileSync('dist/savers.json', JSON.stringify(SAVER_CATALOG, null, 2));

const swiftEntries = SAVER_CATALOG.map(
  (s) => `    SaverEntry(id: ${JSON.stringify(s.id)}, label: ${JSON.stringify(s.label)}),`,
).join('\n');

const swift = `// Generated by web/gen-catalog.mjs — do not edit by hand.
// Source of truth: apps/mac/web/src/savers.ts

struct SaverEntry {
  let id: String
  let label: String
}

enum SaverCatalog {
  static let all: [SaverEntry] = [
${swiftEntries}
  ]
  static var ids: [String] { all.map(\\.id) }
}
`;

writeFileSync('../Sources/IdleScreens/SaverCatalog.swift', swift);
console.log(`catalog: ${SAVER_CATALOG.length} savers → SaverCatalog.swift + savers.json`);
