import type { SaverSpec } from '../types';

/**
 * Control Center: a general-purpose ambient status HUD (home / ops / anything —
 * not dev-specific). Exercises the static/HUD subset at scale plus the
 * v1-ceiling features: `life` staggers the panels in like a boot sequence, a
 * grid-`layout` LED wall breathes behind everything via a traveling
 * `pulse.wave`, `ring` sprites form the central gauge, and a rect "equalizer"
 * animates with a wave-phased pulse. Every panel is keyed so an agent can
 * steer any reading live (`power-value`, `gauge-value`, `feed-1`, ...).
 */
export const DASHBOARD_SPEC: SaverSpec = {
  schemaVersion: 1,
  id: 'dev-dashboard',
  label: 'Control Center',
  seed: 256,
  motionIntensity: 'calm',
  background: {
    type: 'gradient',
    stops: [
      { at: 0, color: '#06060c' },
      { at: 0.5, color: '#0a0a14' },
      { at: 1, color: '#0c0c18' },
    ],
  },
  layers: [
    // --- ambient depth ---
    {
      key: 'dust',
      count: 40,
      sprite: { kind: 'circle', radius: [0.0001852, 0.0007407], color: '#1a2538' },
      alpha: [0.1, 0.25],
      motion: { type: 'drift', speed: [0.0002778, 0.001111], bob: 0.0002778 },
    },
    {
      key: 'led-wall',
      count: 140,
      sprite: { kind: 'circle', radius: [0.0008, 0.0012], color: '#274058' },
      alpha: [0.05, 0.11],
      layout: { type: 'grid', columns: 20, jitter: 0.15 },
      // A slow breath travels diagonally across the wall of dots.
      pulse: { amp: 0.3, period: 5000, wave: { wavelength: 0.35, angle: 20 } },
      motion: { type: 'static' },
    },
    // --- header (boots first) ---
    {
      key: 'title', count: 1,
      position: { x: 0.5, y: 0.045 },
      sprite: { kind: 'text', strings: ['CONTROL CENTER'], color: '#556677',
        font: "600 13px 'SF Mono', monospace", align: 'center' },
      motion: { type: 'static' },
      life: { enter: 200, fade: 600 },
    },
    {
      key: 'status', count: 1,
      position: { x: 0.94, y: 0.045 },
      sprite: { kind: 'text', strings: ['● ALL SYSTEMS GO'], color: '#44cc66',
        font: 'bold 10px monospace', align: 'right' },
      pulse: { amp: 0.2, period: 2400 },
      motion: { type: 'static' },
      life: { enter: 200, fade: 600 },
    },
    {
      key: 'clock', count: 1,
      position: { x: 0.06, y: 0.045 },
      sprite: { kind: 'text', strings: ['21:47'], color: '#8899aa',
        font: 'bold 12px monospace', align: 'left' },
      motion: { type: 'static' },
      life: { enter: 200, fade: 600 },
    },
    // --- left column: readings (boots second) ---
    {
      key: 'power-label', count: 1,
      position: { x: 0.06, y: 0.14 },
      sprite: { kind: 'text', strings: ['POWER'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 700, fade: 600 },
    },
    {
      key: 'power-value', count: 1,
      position: { x: 0.06, y: 0.18 },
      sprite: { kind: 'text', strings: ['3.2 kW'], color: '#ffd166',
        font: 'bold 26px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 700, fade: 600 },
    },
    {
      key: 'network-label', count: 1,
      position: { x: 0.06, y: 0.28 },
      sprite: { kind: 'text', strings: ['NETWORK'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 700, fade: 600 },
    },
    {
      key: 'network-value', count: 1,
      position: { x: 0.06, y: 0.32 },
      sprite: { kind: 'text', strings: ['940 Mb/s'], color: '#44aaff',
        font: 'bold 26px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 700, fade: 600 },
    },
    {
      key: 'climate-label', count: 1,
      position: { x: 0.06, y: 0.42 },
      sprite: { kind: 'text', strings: ['CLIMATE'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 700, fade: 600 },
    },
    {
      key: 'climate-value', count: 1,
      position: { x: 0.06, y: 0.46 },
      sprite: { kind: 'text', strings: ['21.5°'], color: '#44ddcc',
        font: 'bold 26px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 700, fade: 600 },
    },
    {
      key: 'alerts-label', count: 1,
      position: { x: 0.06, y: 0.56 },
      sprite: { kind: 'text', strings: ['ALERTS'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 700, fade: 600 },
    },
    {
      key: 'alerts-value', count: 1,
      position: { x: 0.06, y: 0.60 },
      sprite: { kind: 'text', strings: ['0'], color: '#44cc66',
        font: 'bold 26px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 700, fade: 600 },
    },
    // --- center: energy gauge (boots third) ---
    {
      key: 'gauge-ring', count: 1,
      position: { x: 0.4, y: 0.36 },
      sprite: { kind: 'ring', radius: [0.105, 0.105], color: '#1e3a52', width: 0.0028 },
      alpha: [0.85, 0.85],
      motion: { type: 'static' },
      life: { enter: 1200, fade: 700 },
    },
    {
      key: 'gauge-glow', count: 1,
      position: { x: 0.4, y: 0.36 },
      sprite: { kind: 'ring', radius: [0.088, 0.088], color: '#2ee6c8', width: 0.0016 },
      alpha: [0.55, 0.55],
      blend: 'lighter',
      pulse: { amp: 0.25, period: 4000 },
      grow: { amp: 0.05, period: 4000 },
      motion: { type: 'static' },
      life: { enter: 1200, fade: 700 },
    },
    {
      key: 'gauge-label', count: 1,
      position: { x: 0.4, y: 0.29 },
      sprite: { kind: 'text', strings: ['ENERGY'], color: '#445566',
        font: '9px monospace', align: 'center' },
      motion: { type: 'static' },
      life: { enter: 1200, fade: 700 },
    },
    {
      key: 'gauge-value', count: 1,
      position: { x: 0.4, y: 0.375 },
      sprite: { kind: 'text', strings: ['73%'], color: '#2ee6c8',
        font: 'bold 34px monospace', align: 'center' },
      motion: { type: 'static' },
      life: { enter: 1200, fade: 700 },
    },
    {
      key: 'equalizer',
      count: 22,
      sprite: {
        kind: 'rect',
        width: [0.005, 0.005],
        aspect: [0.6, 3.4],
        color: '#2ee6c8',
        colors: ['#2ee6c8', '#44aaff', '#aa88ff'],
        colorWeights: [3, 2, 1],
      },
      alpha: [0.35, 0.7],
      layout: { type: 'grid', columns: 22 },
      region: { x: [0.28, 0.52], y: [0.585, 0.615] },
      // Wave-phased pulse sweeps along the bars — reads as a live meter.
      pulse: { amp: 0.4, period: 1600, wave: { wavelength: 0.1, angle: 0 } },
      motion: { type: 'static' },
      life: { enter: 1200, fade: 700 },
    },
    // --- right column: agenda + devices (boots fourth) ---
    {
      key: 'agenda-label', count: 1,
      position: { x: 0.64, y: 0.14 },
      sprite: { kind: 'text', strings: ['AGENDA'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 1700, fade: 600 },
    },
    {
      key: 'agenda-1', count: 1,
      position: { x: 0.64, y: 0.19 },
      sprite: { kind: 'text', strings: ['09:00  Standup'], color: '#8899aa',
        font: '11px monospace', align: 'left', baseline: 'top', maxWidth: 0.2593 },
      motion: { type: 'static' },
      life: { enter: 1700, fade: 600 },
    },
    {
      key: 'agenda-2', count: 1,
      position: { x: 0.64, y: 0.23 },
      sprite: { kind: 'text', strings: ['12:30  Lunch w/ Kai'], color: '#778899',
        font: '11px monospace', align: 'left', baseline: 'top', maxWidth: 0.2593 },
      motion: { type: 'static' },
      life: { enter: 1700, fade: 600 },
    },
    {
      key: 'agenda-3', count: 1,
      position: { x: 0.64, y: 0.27 },
      sprite: { kind: 'text', strings: ['18:00  Gym'], color: '#667788',
        font: '11px monospace', align: 'left', baseline: 'top', maxWidth: 0.2593 },
      motion: { type: 'static' },
      life: { enter: 1700, fade: 600 },
    },
    {
      key: 'devices-label', count: 1,
      position: { x: 0.64, y: 0.36 },
      sprite: { kind: 'text', strings: ['DEVICES'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 1700, fade: 600 },
    },
    {
      key: 'devices-1', count: 1,
      position: { x: 0.64, y: 0.41 },
      sprite: { kind: 'text', strings: ['Lights      6 on'], color: '#8899aa',
        font: '11px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 1700, fade: 600 },
    },
    {
      key: 'devices-2', count: 1,
      position: { x: 0.64, y: 0.45 },
      sprite: { kind: 'text', strings: ['Thermostat  eco'], color: '#778899',
        font: '11px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 1700, fade: 600 },
    },
    {
      key: 'devices-3', count: 1,
      position: { x: 0.64, y: 0.49 },
      sprite: { kind: 'text', strings: ['Locks       secured'], color: '#667788',
        font: '11px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 1700, fade: 600 },
    },
    {
      key: 'devices-4', count: 1,
      position: { x: 0.64, y: 0.53 },
      sprite: { kind: 'text', strings: ['Media       paused'], color: '#556677',
        font: '11px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 1700, fade: 600 },
    },
    // --- bottom: activity feed (boots last) ---
    {
      key: 'feed-label', count: 1,
      position: { x: 0.06, y: 0.74 },
      sprite: { kind: 'text', strings: ['ACTIVITY'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
      life: { enter: 2200, fade: 600 },
    },
    {
      key: 'feed-1', count: 1,
      position: { x: 0.06, y: 0.78 },
      sprite: { kind: 'text', strings: ['21:42  Front door locked'], color: '#7a8a7a',
        font: '10px monospace', align: 'left', baseline: 'top', maxWidth: 0.5556 },
      motion: { type: 'static' },
      life: { enter: 2200, fade: 600 },
    },
    {
      key: 'feed-2', count: 1,
      position: { x: 0.06, y: 0.82 },
      sprite: { kind: 'text', strings: ['21:36  Thermostat → eco'], color: '#6a7a6a',
        font: '10px monospace', align: 'left', baseline: 'top', maxWidth: 0.5556 },
      motion: { type: 'static' },
      life: { enter: 2200, fade: 600 },
    },
    {
      key: 'feed-3', count: 1,
      position: { x: 0.06, y: 0.86 },
      sprite: { kind: 'text', strings: ['21:14  Backup completed'], color: '#5a6a5a',
        font: '10px monospace', align: 'left', baseline: 'top', maxWidth: 0.5556 },
      motion: { type: 'static' },
      life: { enter: 2200, fade: 600 },
    },
    {
      key: 'feed-4', count: 1,
      position: { x: 0.06, y: 0.90 },
      sprite: { kind: 'text', strings: ['20:58  Motion · driveway'], color: '#4d5e4d',
        font: '10px monospace', align: 'left', baseline: 'top', maxWidth: 0.5556 },
      motion: { type: 'static' },
      life: { enter: 2200, fade: 600 },
    },
    {
      key: 'feed-5', count: 1,
      position: { x: 0.06, y: 0.94 },
      sprite: { kind: 'text', strings: ['20:41  Sunset scene on'], color: '#3d4e3d',
        font: '10px monospace', align: 'left', baseline: 'top', maxWidth: 0.5556 },
      motion: { type: 'static' },
      life: { enter: 2200, fade: 600 },
    },
  ],
};
