import type { SaverSpec } from '../types';

/**
 * Dev Dashboard: a dense ops-style HUD exercising static positioning, keyed layers,
 * and text alignment at scale. Two ambient particle layers provide depth behind 28
 * pinned text elements arranged in a three-column layout with header, metrics,
 * file list, and scrolling event log.
 */
export const DASHBOARD_SPEC: SaverSpec = {
  schemaVersion: 1,
  id: 'dev-dashboard',
  label: 'Dev Dashboard',
  seed: 256,
  motionIntensity: 'calm',
  background: {
    type: 'gradient',
    stops: [
      { at: 0, color: '#06060c' },
      { at: 0.5, color: '#0a0a14' },
      { at: 1, color: '#0c0c18' },
    ],
  },
  layers: [
    // --- ambient depth ---
    {
      count: 50,
      sprite: { kind: 'circle', radius: [0.0001852, 0.0007407], color: '#1a2538' },
      alpha: [0.1, 0.25],
      motion: { type: 'drift', speed: [0.0002778, 0.001111], bob: 0.0002778 },
    },
    {
      count: 12,
      sprite: { kind: 'circle', radius: [0.0009259, 0.002315], color: '#1a3050', soft: true },
      alpha: [0.08, 0.18],
      blend: 'lighter',
      pulse: { amp: 0.08, period: 4000 },
      motion: { type: 'drift', speed: [0.000463, 0.001389], bob: 0.000463 },
    },
    // --- header ---
    {
      key: 'title', count: 1,
      position: { x: 0.5, y: 0.04 },
      sprite: { kind: 'text', strings: ['DEV PULSE'], color: '#556677',
        font: "600 13px 'SF Mono', monospace", align: 'center' },
      motion: { type: 'static' },
    },
    {
      key: 'status', count: 1,
      position: { x: 0.92, y: 0.04 },
      sprite: { kind: 'text', strings: ['● ACTIVE'], color: '#44cc66',
        font: "bold 10px monospace", align: 'right' },
      motion: { type: 'static' },
    },
    {
      key: 'uptime', count: 1,
      position: { x: 0.08, y: 0.04 },
      sprite: { kind: 'text', strings: ['up 2h 14m'], color: '#445566',
        font: "10px monospace", align: 'left' },
      motion: { type: 'static' },
    },
    // --- left column: metrics ---
    {
      key: 'tools-label', count: 1,
      position: { x: 0.06, y: 0.12 },
      sprite: { kind: 'text', strings: ['TOOL CALLS'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'tools-value', count: 1,
      position: { x: 0.06, y: 0.16 },
      sprite: { kind: 'text', strings: ['147'], color: '#44aaff',
        font: 'bold 28px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'reads-label', count: 1,
      position: { x: 0.06, y: 0.26 },
      sprite: { kind: 'text', strings: ['READS'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'reads-value', count: 1,
      position: { x: 0.06, y: 0.30 },
      sprite: { kind: 'text', strings: ['89'], color: '#44ddcc',
        font: 'bold 28px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'edits-label', count: 1,
      position: { x: 0.06, y: 0.40 },
      sprite: { kind: 'text', strings: ['EDITS'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'edits-value', count: 1,
      position: { x: 0.06, y: 0.44 },
      sprite: { kind: 'text', strings: ['34'], color: '#ff8844',
        font: 'bold 28px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'errors-label', count: 1,
      position: { x: 0.06, y: 0.54 },
      sprite: { kind: 'text', strings: ['ERRORS'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'errors-value', count: 1,
      position: { x: 0.06, y: 0.58 },
      sprite: { kind: 'text', strings: ['2'], color: '#ff4455',
        font: 'bold 28px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    // --- center column: system gauges ---
    {
      key: 'cpu-label', count: 1,
      position: { x: 0.38, y: 0.12 },
      sprite: { kind: 'text', strings: ['CPU'], color: '#445566',
        font: '9px monospace', align: 'center' },
      motion: { type: 'static' },
    },
    {
      key: 'cpu-value', count: 1,
      position: { x: 0.38, y: 0.22 },
      sprite: { kind: 'text', strings: ['73%'], color: '#44ff88',
        font: 'bold 36px monospace', align: 'center' },
      motion: { type: 'static' },
    },
    {
      key: 'mem-label', count: 1,
      position: { x: 0.38, y: 0.36 },
      sprite: { kind: 'text', strings: ['MEMORY'], color: '#445566',
        font: '9px monospace', align: 'center' },
      motion: { type: 'static' },
    },
    {
      key: 'mem-value', count: 1,
      position: { x: 0.38, y: 0.46 },
      sprite: { kind: 'text', strings: ['4.2 GB'], color: '#ddcc44',
        font: 'bold 36px monospace', align: 'center' },
      motion: { type: 'static' },
    },
    {
      key: 'tokens-label', count: 1,
      position: { x: 0.38, y: 0.58 },
      sprite: { kind: 'text', strings: ['TOKENS'], color: '#445566',
        font: '9px monospace', align: 'center' },
      motion: { type: 'static' },
    },
    {
      key: 'tokens-value', count: 1,
      position: { x: 0.38, y: 0.66 },
      sprite: { kind: 'text', strings: ['128k'], color: '#aa88ff',
        font: 'bold 28px monospace', align: 'center' },
      motion: { type: 'static' },
    },
    // --- right column: recent files ---
    {
      key: 'files-label', count: 1,
      position: { x: 0.62, y: 0.12 },
      sprite: { kind: 'text', strings: ['RECENT FILES'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'file-1', count: 1,
      position: { x: 0.62, y: 0.17 },
      sprite: { kind: 'text', strings: ['src/worker.ts'], color: '#8899aa',
        font: '11px monospace', align: 'left', baseline: 'top', maxWidth: 0.2593 },
      motion: { type: 'static' },
    },
    {
      key: 'file-2', count: 1,
      position: { x: 0.62, y: 0.21 },
      sprite: { kind: 'text', strings: ['site/src/App.tsx'], color: '#778899',
        font: '11px monospace', align: 'left', baseline: 'top', maxWidth: 0.2593 },
      motion: { type: 'static' },
    },
    {
      key: 'file-3', count: 1,
      position: { x: 0.62, y: 0.25 },
      sprite: { kind: 'text', strings: ['packages/schema/compile.ts'], color: '#667788',
        font: '11px monospace', align: 'left', baseline: 'top', maxWidth: 0.2593 },
      motion: { type: 'static' },
    },
    {
      key: 'file-4', count: 1,
      position: { x: 0.62, y: 0.29 },
      sprite: { kind: 'text', strings: ['docs/dashboard-spec.md'], color: '#556677',
        font: '11px monospace', align: 'left', baseline: 'top', maxWidth: 0.2593 },
      motion: { type: 'static' },
    },
    {
      key: 'file-5', count: 1,
      position: { x: 0.62, y: 0.33 },
      sprite: { kind: 'text', strings: ['packages/core/types.ts'], color: '#445566',
        font: '11px monospace', align: 'left', baseline: 'top', maxWidth: 0.2593 },
      motion: { type: 'static' },
    },
    // --- right column: session info ---
    {
      key: 'session-label', count: 1,
      position: { x: 0.62, y: 0.42 },
      sprite: { kind: 'text', strings: ['SESSION'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'session-model', count: 1,
      position: { x: 0.62, y: 0.47 },
      sprite: { kind: 'text', strings: ['claude-opus-4-6'], color: '#8888aa',
        font: '11px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'session-cost', count: 1,
      position: { x: 0.62, y: 0.51 },
      sprite: { kind: 'text', strings: ['$2.47 this session'], color: '#667788',
        font: '11px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    // --- bottom: event log ---
    {
      key: 'log-label', count: 1,
      position: { x: 0.06, y: 0.76 },
      sprite: { kind: 'text', strings: ['EVENT LOG'], color: '#445566',
        font: '9px monospace', align: 'left', baseline: 'top' },
      motion: { type: 'static' },
    },
    {
      key: 'log-1', count: 1,
      position: { x: 0.06, y: 0.80 },
      sprite: { kind: 'text', strings: ['14:07  Edit compile.ts +18 -3'], color: '#667766',
        font: '10px monospace', align: 'left', baseline: 'top', maxWidth: 0.5556 },
      motion: { type: 'static' },
    },
    {
      key: 'log-2', count: 1,
      position: { x: 0.06, y: 0.84 },
      sprite: { kind: 'text', strings: ['14:06  Bash pnpm test  ✓ 125 passed'], color: '#556655',
        font: '10px monospace', align: 'left', baseline: 'top', maxWidth: 0.5556 },
      motion: { type: 'static' },
    },
    {
      key: 'log-3', count: 1,
      position: { x: 0.06, y: 0.88 },
      sprite: { kind: 'text', strings: ['14:05  Read types.ts  (121 lines)'], color: '#4d5e4d',
        font: '10px monospace', align: 'left', baseline: 'top', maxWidth: 0.5556 },
      motion: { type: 'static' },
    },
    {
      key: 'log-4', count: 1,
      position: { x: 0.06, y: 0.92 },
      sprite: { kind: 'text', strings: ['14:03  Edit examples/dev-dashboard.ts +84 -1'], color: '#445544',
        font: '10px monospace', align: 'left', baseline: 'top', maxWidth: 0.5556 },
      motion: { type: 'static' },
    },
    {
      key: 'log-5', count: 1,
      position: { x: 0.06, y: 0.96 },
      sprite: { kind: 'text', strings: ['14:01  Bash pnpm build  ✓ 6 packages'], color: '#3d4e3d',
        font: '10px monospace', align: 'left', baseline: 'top', maxWidth: 0.5556 },
      motion: { type: 'static' },
    },
  ],
};
