// Generated by breeds/intake.mjs — do not edit; re-run the intake.
/** The bundled breeds, each a lazy chunk holding its GLB as base64. */
export const BUNDLED_BREEDS: Readonly<Record<string, () => Promise<{ default: string }>>> = {
  babyfish: () => import('./babyfish'),
  blowfish: () => import('./blowfish'),
  crab: () => import('./crab'),
  dori: () => import('./dori'),
  glowfish: () => import('./glowfish'),
  hackerfish: () => import('./hackerfish'),
  starfish: () => import('./starfish'),
  octopus: () => import('./octopus'),
  shark: () => import('./shark'),
};
